services:
  dashboard:
    build: .
    ports:
      - "${PORT:-10000}:10000"
    volumes:
      - .:/app
    environment:
      - PORT=10000
      - PYTHONUNBUFFERED=1
      - MAPBOX_TOKEN=${MAPBOX_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10000"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
