[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python dashboard.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
healthcheckPath = "/health"
healthcheckTimeout = 180
numReplicas = 1

[service]
name = "covid19-dashboard"
internal_port = 8080
healthcheck_path = "/health"

[[ports]]
port = 8080
internal_port = 8080
