[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
buildCommand = "docker build -t app ."

[deploy]
startCommand = "gunicorn -c gunicorn_config.py wsgi:server"
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[service]
name = "covid19-dashboard"
replicas = 1
port = "8080"
