services:
  - type: web
    name: covid19-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dashboard:server -c gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
